# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Let it begin
email: We should decide on a name first
description: > # this means to ignore newlines until "baseurl:"
   Roman cavalry choirs singing. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: Another one
github_username:  Some twitter feed

# Build settings
markdown: kramdown
